{{- if .Values.pgadmin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pgadmin
  labels:
    app: {{ .Release.Name }}-pgadmin
spec:
  replicas: {{ .Values.pgadmin.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pgadmin
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pgadmin
    spec:
      containers:
      - name: pgadmin
        image: "{{ .Values.pgadmin.image.repository }}:{{ .Values.pgadmin.image.tag }}"
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-pgadmin-secrets
              key: pgadmin-email
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-pgadmin-secrets
              key: pgadmin-password
{{- end }}
