apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pgadmin-secrets
  labels:
    app: {{ .Release.Name }}-pgadmin
type: Opaque
data:
  pgadmin-email: {{ .Values.pgAdminEmail | b64enc | quote }}
  pgadmin-password: {{ .Values.pgAdminPassword | b64enc | quote }}
