apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    app: {{ .Release.Name }}-postgresql
spec:
  accessModes:
    - {{ .Values.postgresql.persistence.accessModes | join "," }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size | quote }}
  storageClassName: {{ .Values.postgresql.persistence.storageClass | quote }}
