apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-secrets
  labels:
    app: {{ .Release.Name }}-postgresql
type: Opaque
data:
  postgresql-username: {{ .Values.postgresqlUsername | b64enc | quote }}
  postgresql-password: {{ .Values.postgresqlPassword | b64enc | quote }}
  postgresql-database: {{ .Values.postgresqlDatabase | b64enc | quote }}
